import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./components/layout/Header";
import { Josefin_Sans, Lato } from "next/font/google";
import Footer from "./components/layout/Footer";
import Navbar from "./components/Navbar";
import CartProvider from "./components/Provider";
import { Toaster } from "react-hot-toast";
import { ClerkProvider } from "@clerk/nextjs";
import { WishlistProvider } from "@/context/WishlistContext"; // Import WishlistProvider
import { ShippingProvider } from "../context/ShippingContext";

export const metadata: Metadata = {
  title: "Hecto Figma",
  description: "Generated by create next app",
};

const josefin = Josefin_Sans({
  subsets: ["latin"],
  variable: "--font-josefin",
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

const lato = Lato({
  subsets: ["latin"],
  variable: "--font-lato",
  weight: ["100", "300", "400", "700", "900"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${josefin.variable} ${lato.variable} ${lato.className} overflow-x-hidden antialiased`}
        >
          <CartProvider>
            <WishlistProvider> {/* ✅ Wrapped with WishlistProvider */}
              <ShippingProvider>
                <div className="max-w-[1920px] mx-auto">
                  <Header />
                  <Navbar />
                  <Toaster />
                  {children}
                  <Footer />
                </div>
              </ShippingProvider>
            </WishlistProvider>
          </CartProvider>

        </body>
      </html>
    </ClerkProvider>
  );
}
